### ISSUE TITLE
twauctex-electric-regexes is redefined on emacs startup

### ISSUE THREAD

**Issue by cpeikert** [jeeger/twauctex#10]
I am not sure if this is a twauctex bug per se, but I cannot figure out the cause or what the fix might be.

Upon emacs (Mac port) startup, `twauctex-electric-regexes` is defined as `\([.?!…‽][]"'”’)}»›]*\($\|[  ]$\|	\|[  ][  ]\)\|[。．？！]+\)[  	`. This prevents proper line-breaking from occurring.

`customize-variable` says that this variable is "CHANGED outside Customize". When I choose "Erase Customization", line-breaking works as desired. Annoyingly, I have to do this every time emacs loads.

I use a number of other emacs packages, but loading twauctex earlier/later does not seem to help.

Any ideas what could be causing this? Here is my relevant (tw)auctex setup:

```
(add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)
(add-hook 'LaTeX-mode-hook 'turn-on-reftex)
(add-hook 'LaTeX-mode-hook 'turn-on-bib-cite)
(add-hook 'LaTeX-mode-hook 'turn-on-flyspell)
(add-hook 'TeX-update-style-hook 'rainbow-delimiters-mode)

(require 'twauctex)
(twauctex-global-mode)

;; add latexmk support to auctex
(provide 'tex-buf)                      ; workaround
(require 'auctex-latexmk)
(auctex-latexmk-setup)
```

**Comment by cpeikert** [comment]
Update: I found the cause and a workaround, but it is brittle and there is probably a better way.

The cause: when `twauctex` is loaded, it sets the customizable variable `twauctex-electric-regexes` to the value of `(sentence-end)`. But `sentence-end` (when the variable of the same name is nil, as it is by default) _builds_ a regex from several other customizable values, including `sentence-end-double-space`.

My configuration disables `sentence-end-double-space`, but only at the _end_ of startup, via the auto-generated `custom-set-variables`. This has the effect of changing the value of `sentence-end`, but only after `twauctex-electric-regexes` has already been set.

A workaround is to do `(customize-set-variable 'sentence-end-double-space nil)` _before_ loading `twauctex`. With this change, `twauctex-electric-regexes` shows as "STANDARD" in Customize, and line-breaking works as desired.

This is obviously a clumsy and brittle solution. A better one might be to automatically update the value of `twauctex-electric-regexes` whenever the value returned by `sentence-end` would change, _if_ the former has not already been customized. But I do not know enough elisp to implement this kind of behavior.

**Comment by jeeger** [comment]
Thanks for the heads up! This is indeed a problem. I'll have a look at it one of these days.

**Comment by jeeger** [comment]
Hello! Maybe you can try the fix_issue_10 branch, where I've moved the use of `sentence-end` into the initialisation of twauctex-mode. This should fix your problem.

**Comment by cpeikert** [comment]
Thank you! It seems to work great (with some brief usage).
