### ISSUE TITLE
Full sentences inside parentheses

### ISSUE THREAD

**Issue by apc** [jeeger/twauctex#2]
At the moment, typing `SPC` after this

```
(This is a sentence.)
```

does not insert a new line. I can't quite figure out how to make the relevant change myself, but I suspect it would require modifying `twauctex--update-electric-regexp` so that it can take a list of strings and not just a list of characters. 

Thanks for this nice package!

**Comment by jeeger** [comment]
I've implemented this in 64bcc52. You can now add a regex like "\\\\.)" to make this regex electric.

**Comment by apc** [comment]
Works like a charm!

**Comment by apc** [comment]
I take it the list can be modified from outside `twauctex.el` using something like `setq` or  `add-to-list`? (Ditto for `twauctex-non-break-abbrevs`?)

**Comment by jeeger** [comment]
Beware! You can customize `twauctex-electric-regexes`, but don't modify the `twauctex--*` variables. These are internal, and any changes you do will be overwritten.

Now that we've implemented this, there's no real reason not to use `(sentence-end)` as one of the regexes. hum.

**Comment by apc** [comment]
You're thinking using `(sentence-end)` here won't have the same issues you mentioned earlier? If so, that'd be nice!

**Comment by jeeger** [comment]
See a75f1d2ae9907591a93462836b098cdf81389c24.
