### ISSUE TITLE
Error message triggered by `^[A-Za-z]\.` when not inside `document` environment

### ISSUE THREAD

**Issue by apc** [jeeger/twauctex#3]
After opening the `*scratch*` buffer, setting `LaTeX-mode` on, and calling `twauctex-mode`, typing a two letter string followed by `.`+`SPC` gives this error message: 

```
looking-back: Invalid search bound (wrong side of point)
```

Interestingly it only happens on the first line of text. In other words, hitting `SPC` after the `p.` on the second line here

```
This
p.
```

works as expected. But hitting `SPC` after the `p.` on the first line here

```
p.
```

does not. Also, if there's more than two empty lines above, `SPC` after `p.` works just fine. 

`¯\_(ツ)_/¯`

The same behavior occurs with an existing `.tex` file, as long as the point is after `.` following:

- up to two characters on the first line of the document
- up to one character on the second line of the document as long as the first line is empty.

Hitting `SPC` in any such scenario yields the above error message.

**Comment by jeeger** [comment]
I can't reproduce this. Are you sure this isn't a result of your attempts with `twauctex-electric-chars'?

If you've restarted and reverted the files to the git version, could you provide a debug backtrace with `(toggle-debug-on-error)`?

**Comment by apc** [comment]
I'm just working with the `electric-space` branch of this repo. (I switched to a local branch before trying to make changes.) This is what I get using `(toggle-debug-on-error)`: 

```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-backward("\\(?:[[:upper:]][!.?]\\)\\=" 5 t)
  looking-back("[[:upper:]][!.?]" 5)
  (let* ((case-fold-search nil) (repeated (or (> arg 1) (eq last-command (quote twauctex-electric-sentence-end-space)))) (in-environment (member (LaTeX-current-environment) twauctex-electric-environments)) (inhibited-macro (member (TeX-current-macro) twauctex-inhibited-electric-macros)) (at-abbrev (twauctex-looking-at-abbrev)) (at-electric (looking-back twauctex--electric-regexp 1)) (at-lastupper (looking-back (concat "[[:upper:]]" twauctex--electric-regexp) 5))) (cond ((and repeated (bolp)) (delete-char -1) (self-insert-command 1)) ((and in-environment (not inhibited-macro) (not at-abbrev) at-electric (not (TeX-in-comment))) (if (and at-lastupper twauctex-insert-sentence-spacing) (progn (backward-char 1) (insert "\\@") (forward-char 1))) (newline)) ((and at-abbrev at-electric twauctex-insert-word-spacing) (insert "\\ ")) (t (self-insert-command 1))))
  twauctex-electric-sentence-end-space(1)
  funcall-interactively(twauctex-electric-sentence-end-space 1)
  call-interactively(twauctex-electric-sentence-end-space nil nil)
  command-execute(twauctex-electric-sentence-end-space)
```

Let me know if there's something else I should do?

**Comment by apc** [comment]
OK, after pulling recent changes this error went away. I have no clue what happened!

**Comment by jeeger** [comment]
I might have done a sneaky force push☺
